### ISSUE TITLE
Landing page is login page

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#140] opened 2018-08-13 06:59 UTC
After the login user does not need to see again the login page.

**Comment by sventhiel** [comment] 2018-08-15 06:48
After Login, there is a redirect based on an information inside `General.Settings.xml`. Unfortunately, the following line of code isn't returning true. 

`if (!this.IsAccessible(moduleName, controllerName, actionName))`

That is the reason why the system redirects the user to `Host/Home/Index` - which is obviously the login page.

- [ ] Improve `Home/Index` to either shwo register/login information or other stuff (based on the status of the user - (un)authenticated)
- [ ] Fix the check for redirect after login

**Comment by javadch** [comment] 2018-08-16 13:40
The check for redirection works as designed in both debug and release modes.

**Comment by DavidBlaa** [comment] 2018-08-21 07:09
it seems not to fixed in the v2.12 rc

- i check the manifestfile 
![image](https://user-images.githubusercontent.com/19665289/44386012-7d549880-a521-11e8-8d74-702f8a52bce0.png)

- the general settings in site
![image](https://user-images.githubusercontent.com/19665289/44386035-965d4980-a521-11e8-8fe9-5bead1a1b3bd.png)

- manifest file
![image](https://user-images.githubusercontent.com/19665289/44386113-dd4b3f00-a521-11e8-9150-dcc4cfc42ad8.png)

**Comment by javadch** [comment] 2018-08-21 09:43
I tested it in debug and release modes while connected to the server's DB; everything works fine. Maybe we have to republish the code!

**Comment by DavidBlaa** [comment] 2018-08-22 07:32
works in v2.12 rc 4

**Closed** 2018-08-22 07:35 UTC
Labels: 2.12 RC3, Priority: Medium, Status: Completed, Type: Bug
