### ISSUE TITLE
Tab Overlay

### ISSUE THREAD

**Issue by navabpourn** [BEXIS2/Core#257] opened 2019-05-10 08:29 UTC
**Is your feature request related to a problem? Please describe.**
Frequently the metadata page does not completely disappear when I go through tabs.
It bothers if I have to refresh the page frequently and re-select the tab.

**Screenshot**
![SharedScreenshot](https://user-images.githubusercontent.com/20185586/57513089-b336e880-730d-11e9-8cbd-f06210818a6c.jpg)

**System**
- SPP 2089 instance
- BEXIS2.12.3

**Comment by sventhiel** [comment] 2019-11-25 16:22
Hi @navabpourn,

After some tests, I was able to reproduce that issue. Probably, it is related to the "refresh/reload" of the page. Because it is "ugly", but not that crucial, we won't solve it for the upcoming release. But I am going to put it into the next one (patch afterwards).

**Comment by sventhiel** [comment] 2020-02-05 09:06
Because that issue is more an enhancement instead of a bug and "low" priority, I would like to close it. So if there is no further discussion/feedback within the next seven days I am going to close it.

**Comment by navabpourn** [comment] 2020-02-05 10:45
It happens frequently and it is up to you whether you close it.

**Closed** 2020-02-19 09:15 UTC
Labels: Priority: Low, Type: Enhancement
