### ISSUE TITLE
DCM - Attachments 500 Error (not logged in)

### ISSUE THREAD

**Issue by geofranzi** [BEXIS2/Core#104] opened 2018-07-26 09:52 UTC
- not logged in 
- view dataset
- click on Attachments

![image](https://user-images.githubusercontent.com/15946467/43255381-f6c4b234-90c9-11e8-865f-23c657a67fd7.png)

**Comment by matparsa** [comment] 2018-08-06 09:16
I couldn't reproduce the issue. Maybe it was before the pushing my last changes to the release. This screenshot is for my current code which I am not logged in and the attachments tab is disabled for me.
![image](https://user-images.githubusercontent.com/14373134/43708161-1efd5d2a-996a-11e8-8bbc-ce054b41a4ae.png)

**Comment by navabpourn** [comment] 2018-08-10 08:14
I am able to produce it in RC2 :(

**Comment by DavidBlaa** [comment] 2018-08-17 12:45
now you can try it again

**Comment by matparsa** [comment] 2018-08-18 09:48
it should be fixed now.

**Comment by DavidBlaa** [comment] 2018-08-22 09:55
![image](https://user-images.githubusercontent.com/19665289/44456881-1064ff80-a602-11e8-86c1-2cc7a1a193b0.png)

**Comment by matparsa** [comment] 2018-09-01 05:06
in RC4 it's correct.
![image](https://user-images.githubusercontent.com/14373134/44942592-7cd7bf80-adb5-11e8-9a62-eb883ab3831c.png)

**Comment by romangerlach** [comment] 2019-01-29 10:54
solved

**Closed by romangerlach** 2019-01-29 10:54 UTC
Labels: Status: Testing Required, Type: Bug
