### ISSUE TITLE
User have to click Save button twice on the metadata page to save the content

### ISSUE THREAD

**Issue by jitendragaikwad** [BEXIS2/Core#1042] opened 2023-01-05 13:30 UTC
**Describe the bug**
 It takes really long to save metadata changes. For the user, it is not visible that in the background the metadata is getting saved or the system is working. Usually, in such cases, the user becomes impatient and clicks the save button again and it seems the process gets completed. As a result, the user ends up clicking the save button 2 times.

**To Reproduce**
1. Go to metadata edit or write page/form
2. Click on the save button
3. See no indication that the metadata is getting saved
4. Have to  click the save button one more time

**Expected behavior**
When a save button is clicked it becomes deactivated indicating that the content is getting saved in the system. This will also restrict the user from clicking twice.

**Actual behavior**
See above in the 'To Reproduce# section

**Comment by sventhiel** [comment] 2023-01-16 13:38
Duplicate of #702

**Closed by sventhiel** 2023-01-16 13:38 UTC
